version: 0.0
os: Linux

files:
  - source: /
    destination: /home/ubuntu/jenkins/learnbay
    overwrite: true

#only work for Linux
permissions:
  - object: /home/ubuntu/jenkins/learnbay
    pattern: "**"
    owner: ec2_user
    group: ec2_user
    mode: 755
    type:
      - file
      - directory

#deployment lifecycle hooks
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root 
  DownloadBundle:
    - location: scripts/download_bundle.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/app_configuration.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh 
      timeout: 300
      runas: root



